Repository openstack-k8s-operators/data-plane-adoption, pull requests merged in 2025-01, with the labels that each got.

#769 adoption uni01alpha - ironic ServiceNetMap
  scenarios/uni01alpha/config_download.yaml
  scenarios/uni01alpha/network_data.yaml.j2
  scenarios/uni01alpha/roles.yaml
  scenarios/uni01alpha/vips_data.yaml
Labels: Stale

#710 Fix Swift migration tests and remove fixed IP
  docs_user/modules/proc_migrating-object-storage-data-to-rhoso-nodes.adoc
  tests/roles/swift_migration/tasks/main.yaml
Labels: to-backport, Stale

#763 Add Barbican to OSP17.1 scenarios tested for adoption
  scenarios/hci.yaml
  scenarios/hci/config_download.yaml
  scenarios/uni01alpha.yaml
  scenarios/uni01alpha/config_download.yaml
Labels: to-backport

#787 Fix pre-commit config and ansible-lint
  .ansible-lint
  .pre-commit-config.yaml
Labels: lgtm, approved

#780 Rendering for Director Operator docs variant Fixes
  Makefile
  docs_user/Makefile
  docs_user/adoption-attributes.adoc
  docs_user/assemblies/assembly_ospdo-scale-down-pre-database-adoption.adoc
  docs_user/assemblies/assembly_prepare-director-operator-and-rhoso-for-adoption-process.adoc
  docs_user/main.adoc
  docs_user/modules/con_troubleshooting-object-storage-migration.adoc
  docs_user/modules/proc_adopting-compute-services-to-the-data-plane.adoc
  docs_user/modules/proc_adopting-image-service-with-nfs-backend.adoc
  docs_user/modules/proc_deploying-backend-services.adoc
  docs_user/modules/proc_deploying-file-systems-service-control-plane.adoc
  docs_user/modules/proc_migrating-databases-to-mariadb-instances.adoc
  docs_user/modules/proc_migrating-ovn-data.adoc
  docs_user/modules/proc_migrating-tls-everywhere.adoc
  docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
Labels: lgtm, approved

#790 formatting changes in ospdo docs
  docs_user/Makefile
  docs_user/assemblies/assembly_prepare-director-operator-and-rhoso-for-adoption-process.adoc
  docs_user/main.adoc
  docs_user/modules/proc_deploying-backend-services.adoc
  docs_user/modules/proc_migrating-ovn-data.adoc
  docs_user/modules/proc_migrating-tls-everywhere.adoc
  docs_user/modules/proc_ospdo-scale-down-pre-database-adoption.adoc
  docs_user/modules/proc_preparing-RHOSO-for-director-operator-adoption.adoc
  docs_user/modules/proc_preparing-controller-nodes-for-director-operator-adoption.adoc
  docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
Labels: lgtm, approved

#788 CI changes backport 18.0 fr1
  .ci-operator.yaml
  .github/workflows/docs.yaml
  .github/workflows/lint.yaml
  .github/workflows/stale-pr.yml
  .yamllint.yml
  OWNERS
Labels: lgtm

#792 removed recommendations
  docs_user/assemblies/assembly_preparing-the-block-storage-service-for-adoption.adoc
  docs_user/modules/con_block-storage-service-requirements.adoc
  docs_user/modules/con_openshift-preparation-for-block-storage-adoption.adoc
  docs_user/modules/con_preparing-the-shared-file-systems-service-configuration.adoc
  docs_user/modules/proc_adopting-the-block-storage-service.adoc
  docs_user/modules/proc_decommissioning-rhosp-standalone-ceph-NFS-service.adoc
Labels: lgtm, approved

#793 added optional step to power off controllers
  docs_user/modules/con_adoption-process-overview.adoc
Labels: lgtm, approved

#783 ovn: Always set replicas=3 for ovn dbs
  docs_user/modules/proc_deploying-backend-services.adoc
  docs_user/modules/proc_migrating-ovn-data.adoc
  tests/roles/backend_services/templates/openstack_control_plane.j2
  tests/roles/backend_services/templates/openstack_control_plane_ospdo.j2
  tests/roles/ovn_adoption/defaults/main.yaml
Labels: lgtm, approved

#795 Add make openstack_init to adoption docs
  docs_dev/assemblies/development_environment.adoc
  docs_user/modules/proc_preparing-RHOSO-for-director-operator-adoption.adoc
Labels: lgtm

#797 minor formatting changes in octavia adoption procedure
  docs_user/adoption-attributes.adoc
  docs_user/modules/proc_adopting-the-loadbalancer-service.adoc
Labels: lgtm, approved

#781 Ignore mysql version mismatch for upgrade w/a
  tests/roles/get_services_configuration/tasks/main.yaml
Labels: lgtm, approved
