Repository openstack-k8s-operators/data-plane-adoption, pull requests merged in 2025-03, with the labels that each got.

#830 Fix glance replica number in the NFS adoption guide
  docs_user/modules/proc_adopting-image-service-with-nfs-backend.adoc
Labels: lgtm, approved

#834 minor grammar edits
  docs_user/modules/proc_adopting-the-block-storage-service.adoc
Labels: lgtm, approved

#832 Fix Swift ring update race condition
  docs_user/modules/proc_migrating-object-storage-data-to-rhoso-nodes.adoc
  tests/roles/swift_migration/tasks/main.yaml
Labels: lgtm, approved

#836 Bump Rabbit PVC to 3Gi
  tests/roles/backend_services/templates/openstack_control_plane.j2
Labels: lgtm, approved

#831 Fix select DB to omit deleted hosts
  docs_user/modules/proc_migrating-databases-to-mariadb-instances.adoc
  docs_user/modules/proc_performing-a-fast-forward-upgrade-on-compute-services.adoc
  docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
  tests/roles/dataplane_adoption/tasks/nova_ffu.yaml
  tests/roles/get_services_configuration/tasks/main.yaml
  tests/roles/mariadb_copy/templates/post_checks.bash
Labels: lgtm, approved

#841 specified base64 encoded password
  docs_user/modules/proc_adopting-compute-services-to-the-data-plane.adoc
  docs_user/modules/proc_performing-a-fast-forward-upgrade-on-compute-services.adoc
Labels: lgtm, approved

#835 test_with_ironic use get_services_configuration
  tests/playbooks/test_with_ironic.yaml
Labels: lgtm, approved

#674 Hugepages test vm
  docs_dev/assemblies/development_environment.adoc
  docs_user/modules/proc_adopting-compute-services-to-the-data-plane.adoc
  tests/roles/dataplane_adoption/defaults/main.yaml
  tests/roles/development_environment/defaults/main.yaml
  tests/roles/development_environment/files/pre_launch.bash
  tests/roles/development_environment/tasks/main.yaml
  tests/vars.sample.yaml
Labels: lgtm, approved

#848 remove base64-encoded
  docs_user/modules/proc_adopting-compute-services-to-the-data-plane.adoc
Labels: lgtm, approved

#850 Remove instructions for base64-encoding where not applicable
  docs_user/modules/proc_adopting-compute-services-to-the-data-plane.adoc
Labels: lgtm, approved

#851 [18.0-fr2] remove base64-encoded
  docs_user/modules/proc_adopting-compute-services-to-the-data-plane.adoc
Labels: lgtm, approved

#852 [18.0-fr2] Remove instructions for base64-encoding where not applicable
  docs_user/modules/proc_adopting-compute-services-to-the-data-plane.adoc
Labels: lgtm, approved

#775 uni06zeta scenario 17.1 for adoption
  scenarios/uni06zeta.yaml
  scenarios/uni06zeta/config_download.yaml
  scenarios/uni06zeta/hieradata_overrides_undercloud.yaml
  scenarios/uni06zeta/network_data.yaml.j2
  scenarios/uni06zeta/roles.yaml
  scenarios/uni06zeta/undercloud_parameter_defaults.yaml
  scenarios/uni06zeta/vips_data.yaml
Labels: lgtm, approved

#859 Optional Octavia SSH adoption test
  tests/roles/octavia_adoption/defaults/main.yaml
  tests/roles/octavia_adoption/tasks/octavia_ssh.yaml
Labels: lgtm, approved

#846 Make ironic network name configurable
  tests/roles/ironic_adoption/defaults/main.yaml
  tests/vars.sample.yaml
Labels: lgtm, approved

#853 nova_adoption: ironic, FFU patch remove optional
  tests/roles/nova_adoption/defaults/main.yaml
  tests/roles/nova_adoption/tasks/nova_ironic.yaml
Labels: lgtm, approved

#857 Add Barbican to OSP17.1 uni06zeta
  scenarios/uni06zeta.yaml
  scenarios/uni06zeta/config_download.yaml
Labels: lgtm, approved, ok-to-test

#774 Add tobiko to adoption job
  tests/roles/dataplane_adoption/tasks/neutron_verify.yaml
Labels: lgtm, approved

#855 Apply required ospdo changes to adoption docs
  docs_user/adoption-attributes.adoc
  docs_user/assemblies/assembly_adopting-the-data-plane.adoc
  docs_user/modules/con_adoption-limitations.adoc
  docs_user/modules/con_adoption-prerequisites.adoc
  docs_user/modules/con_adoption-process-overview.adoc
  docs_user/modules/con_comparing-configuration-files-between-deployments.adoc
  docs_user/modules/proc_adopting-compute-services-to-the-data-plane.adoc
  docs_user/modules/proc_adopting-image-service-with-ceph-backend.adoc
  docs_user/modules/proc_deploying-backend-services.adoc
  docs_user/modules/proc_migrating-databases-to-mariadb-instances.adoc
  docs_user/modules/proc_migrating-ovn-data.adoc
  docs_user/modules/proc_ospdo-scale-down-pre-database-adoption.adoc
  docs_user/modules/proc_preparing-RHOSO-for-director-operator-adoption.adoc
  docs_user/modules/proc_preparing-controller-nodes-for-director-operator-adoption.adoc
  docs_user/modules/proc_retrieving-network-information-from-your-existing-deployment.adoc
  docs_user/modules/proc_stopping-openstack-services.adoc
  docs_user/modules/proc_using-new-subnet-ranges.adoc
  tests/roles/common_defaults/defaults/main.yaml
Labels: lgtm, approved

#833 Update ceph dashboard port
  docs_user/modules/proc_migrating-mgr-from-controller-nodes.adoc
Labels: lgtm, approved

#862 Tobiko adoption move to developement environmnet role
  tests/roles/dataplane_adoption/tasks/neutron_verify.yaml
  tests/roles/development_environment/tasks/main.yaml
Labels: lgtm, approved, needs-ok-to-test

#860 Ironic API override internal service to ctlplane
  tests/roles/ironic_adoption/defaults/main.yaml
Labels: lgtm, approved

#867 added source tag on code blocks with hashtags
  docs_user/modules/proc_deploying-backend-services.adoc
  docs_user/modules/proc_migrating-mgr-from-controller-nodes.adoc
  docs_user/modules/proc_migrating-mon-from-controller-nodes-config-target-nodes.adoc
  docs_user/modules/proc_migrating-the-rgw-backends.adoc
  docs_user/modules/proc_pulling-configuration-from-a-tripleo-deployment.adoc
  docs_user/modules/proc_stopping-openstack-services.adoc
  docs_user/modules/proc_using-new-subnet-ranges.adoc
Labels: lgtm, approved

#865 updates from ironic testing
  docs_user/assemblies/assembly_adopting-openstack-control-plane-services.adoc
  docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
Labels: lgtm, approved

#849 Allow customizing the test log file path
  Makefile
Labels: lgtm, approved

#874 Fixed incorrect grep in octavia adoption
  docs_user/modules/proc_adopting-the-loadbalancer-service.adoc
  tests/roles/octavia_adoption/tasks/octavia_cr_config.yaml
Labels: lgtm, approved

#517 Multi-cell adoption
  docs_dev/assemblies/development_environment.adoc
  docs_dev/assemblies/tests.adoc
  docs_user/modules/con_adoption-limitations.adoc
  docs_user/modules/proc_adopting-compute-services-to-the-data-plane.adoc
  docs_user/modules/proc_adopting-the-compute-service.adoc
  docs_user/modules/proc_configuring-data-plane-nodes.adoc
  docs_user/modules/proc_deploying-backend-services.adoc
  docs_user/modules/proc_migrating-databases-to-mariadb-instances.adoc
  docs_user/modules/proc_performing-a-fast-forward-upgrade-on-compute-services.adoc
  docs_user/modules/proc_retrieving-topology-specific-service-configuration.adoc
  tests/roles/backend_services/templates/openstack_control_plane.j2
  tests/roles/common_defaults/defaults/main.yaml
  tests/roles/control_plane_rollback/defaults/main.yaml
  tests/roles/dataplane_adoption/defaults/main.yaml
  tests/roles/dataplane_adoption/tasks/main.yaml
  tests/roles/dataplane_adoption/tasks/nova_ffu.yaml
  tests/roles/nova_adoption/defaults/main.yaml
  tests/roles/nova_adoption/tasks/nova_ironic.yaml
  tests/roles/nova_adoption/tasks/nova_libvirt.yaml
  tests/roles/nova_adoption/tasks/wait.yaml
  tests/roles/ovn_adoption/tasks/main.yaml
  tests/vars.sample.yaml
Labels: lgtm, approved

#861 Add more services and tags to test_with_ironic.yaml
  tests/playbooks/test_with_ironic.yaml
Labels: lgtm, approved
